In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. Phoneme Dataset
Load the phoneme dataset using Pandas

In [80]:
data = pd.read_csv('data/phoneme.csv')
data["Split_param"] = data['speaker'].str.split(".", n=1, expand=False).str[0]
#print(data)

# TODO 
# Split the dataset into a train and test dataset according to column "speaker".
# Be sure to exclude row number, "speaker" and response columns from your features.

train_data = data[data['Split_param'] == 'train']
train_response=train_data['g'].to_list()

drop_cols=['Split_param','speaker','g','row.names']
train_data=train_data.drop(drop_cols, axis=1)

test_data = data[data['Split_param'] == 'test']
test_response=test_data['g'].to_list()
test_data=test_data.drop(drop_cols, axis=1)


### 2. LDA modelling
Fit an LDA model. Compute and report the train and test error.

In [81]:
# TODO
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

lda = LinearDiscriminantAnalysis()
model = lda.fit(train_data, train_response)

pred_train=model.predict(train_data).tolist()


i=0
for ele1,ele2 in zip(pred_train,train_response):
    if(ele1==ele2):
        i=i+1
train_error=1-(i/(len(train_response)))
print("Train Error:",train_error)
    

pred_test=model.predict(test_data).tolist()
i=0
for ele1,ele2 in zip(pred_test,test_response):
    if(ele1==ele2):
        i=i+1
test_error=1-(i/(len(test_response)))

print("Test Error:",test_error)
    



Train Error: 0.05598802395209579
Test Error: 0.08041060735671512


In [82]:
#defining a function for finding confusion matrix and obtain the error rate from the confusion matrix
def error_from_confusion_matrix(train, response):
    tot_all=0
    tot_correct=0
    con=confusion_matrix(train,response)


    for i in range (len(con)):
    
        y1=np.array(con[i])
        print(y1)
        for j in range(len(y1)):
            tot_all= tot_all+y1[j]
        tot_correct= tot_correct+y1[i]

    error_rate= (tot_all-tot_correct)/tot_all
    print("the error rate is",error_rate)
    
    

In [83]:
#Verifying the Train Error and Test Error obtained Using the Confusion Matrix
print("For training data the confusion matrix is")
error_from_confusion_matrix(pred_train,train_response)
print("For test data the confusion matrix is")
error_from_confusion_matrix(pred_test,test_response)


For training data the confusion matrix is
[424  82   0   0   0]
[ 95 677   0   0   0]
[  0   0 553   1   0]
[  0   0   8 851   0]
[  0   0   1   0 648]
the error rate is 0.05598802395209581
For test data the confusion matrix is
[129  39   0   0   0]
[ 47 223   0   0   0]
[  0   0 190   2   0]
[  0   1   5 309   0]
[  0   0   0   0 224]
the error rate is 0.08041060735671514


### 3. LDA canonical coordinates
 Plot the projection of the training data onto the first two canonical coordinates of the LDA and report your findings. Investigate the data projected on further dimensions using the \texttt{dimen} parameter.

In [84]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import matplotlib.pyplot as plt

lda_dimensionality_reduction = LinearDiscriminantAnalysis(n_components = 2)
training_of_x = lda_model.fit_transform(train_data, train_response)
testing_of_x= lda_model.transform(test_data)



### 4. LDA on "aa", "ao"
Select the two phonemes "aa" and "ao". Fit an LDA model on this data set and repeat the steps
    done in (2).

In [85]:
# TODO
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

# TODO
#Train Set
train_data_aa_ao =data[data['Split_param'] == 'train']



train_data_aa= train_data_aa_ao[train_data_aa_ao['g'] == 'ao']
train_data_ao = train_data_aa_ao[train_data_aa_ao['g'] == 'aa']
train_data_aa_ao = train_data_aa.append(train_data_ao)



train_response_aa_ao=train_data_aa_ao['g'].to_list()
train_data_aa_ao=train_data_aa_ao.drop(drop_cols, axis=1)

#Test Set
test_data_aa_ao =data[data['Split_param'] == 'test']

test_data_aa= test_data_aa_ao[test_data_aa_ao['g'] == 'ao']
test_data_ao = test_data_aa_ao[test_data_aa_ao['g'] == 'aa']
test_data_aa_ao = test_data_aa.append(test_data_ao)




test_response_aa_ao=test_data_aa_ao['g'].to_list()
test_data_aa_ao=test_data_aa_ao.drop(drop_cols, axis=1)


#Fitting the model
lda_aa_ao = LinearDiscriminantAnalysis()
model_aa_ao = lda_aa_ao.fit(train_data_aa_ao, train_response_aa_ao)

pred_train_aa_ao=model_aa_ao.predict(train_data_aa_ao).tolist()


i=0
for ele1,ele2 in zip(pred_train_aa_ao,train_response_aa_ao):
    if(ele1==ele2):
        i=i+1

train_error_aa_ao=1-(i/(len(train_response_aa_ao)))
print("Train Error for aa/ao:",train_error_aa_ao)
    

pred_test_aa_ao=model_aa_ao.predict(test_data_aa_ao).tolist()
i=0
for ele1,ele2 in zip(pred_test_aa_ao,test_response_aa_ao):
    if(ele1==ele2):
        i=i+1
test_error_aa_ao=1-(i/(len(test_response_aa_ao)))
print("Test Error for aa/ao:",test_error_aa_ao)


Train Error for aa/ao: 0.10641627543035992
Test Error for aa/ao: 0.214123006833713


## 5. QDA
Repeat steps (b) and (d) using QDA and report your findings. Would you prefer LDA or QDA in this example? Why?

In [86]:
# TODO QDA of b
#Fit an qda model. Compute and report the train and test error.
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

qda = QuadraticDiscriminantAnalysis()
model = qda.fit(train_data,train_response)

pred_train=model.predict(train_data).tolist()


i=0
for ele1,ele2 in zip(pred_train,train_response):
    if(ele1==ele2):
        i=i+1
train_error=1-(i/(len(train_response)))
print("Train Error:",train_error)
    

pred_test=model.predict(test_data).tolist()
i=0
for ele1,ele2 in zip(pred_test,test_response):
    if(ele1==ele2):
        i=i+1
test_error=1-(i/(len(test_response)))

print("Test Error:",test_error)
    


Train Error: 0.0
Test Error: 0.1582549187339607


In [87]:
# TODO
#Select the two phonemes "aa" and "ao". Fit an LDA model on this data set and repeat the steps done in (2).
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

# TODO
#Train Set
train_data_aa_ao_qda =data[data['Split_param'] == 'train']



train_data_aa_qda= train_data_aa_ao_qda[train_data_aa_ao_qda['g'] == 'ao']
train_data_ao_qda = train_data_aa_ao_qda[train_data_aa_ao_qda['g'] == 'aa']
train_data_aa_ao_qda= train_data_aa_qda.append(train_data_ao_qda)



train_response_aa_ao_qda=train_data_aa_ao_qda['g'].to_list()
train_data_aa_ao_qda=train_data_aa_ao_qda.drop(drop_cols, axis=1)

#Test Set
test_data_aa_ao_qda =data[data['Split_param'] == 'test']

test_data_aa_qda= test_data_aa_ao_qda[test_data_aa_ao_qda['g'] == 'ao']
test_data_ao_qda= test_data_aa_ao_qda[test_data_aa_ao_qda['g'] == 'aa']
test_data_aa_ao_qda = test_data_aa_qda.append(test_data_ao_qda)




test_response_aa_ao_qda=test_data_aa_ao_qda['g'].to_list()
test_data_aa_ao_qda=test_data_aa_ao_qda.drop(drop_cols, axis=1)


#Fitting the model
qda_aa_ao = QuadraticDiscriminantAnalysis()
model_aa_ao = qda_aa_ao.fit(train_data_aa_ao_qda, train_response_aa_ao_qda)

pred_train_aa_ao_qda=model_aa_ao.predict(train_data_aa_ao_qda).tolist()


i=0
for ele1,ele2 in zip(pred_train_aa_ao_qda,train_response_aa_ao_qda):
    if(ele1==ele2):
        i=i+1

train_error_aa_ao_qda=1-(i/(len(train_response_aa_ao_qda)))
print("Train Error for aa/ao:",train_error_aa_ao_qda)
    

pred_test_aa_ao_qda=model_aa_ao.predict(test_data_aa_ao_qda).tolist()
i=0
for ele1,ele2 in zip(pred_test_aa_ao_qda,test_response_aa_ao_qda):
    if(ele1==ele2):
        i=i+1
test_error_aa_ao_qda=1-(i/(len(test_response_aa_ao_qda)))
print("Test Error for aa/ao:",test_error_aa_ao_qda)



Train Error for aa/ao: 0.0
Test Error for aa/ao: 0.33940774487471526


## 6. Confusion Matrices
Generate confusion matrices for the LDA and QDA model for "aa" and "ao". Which differences can you observe between the models?

In [88]:
# TODO 
print("confusion matrices for the LDA for aa and ao")
print(confusion_matrix(pred_train_aa_ao, train_response_aa_ao))
print("confusion matrices for the QDA for aa and ao")
print(confusion_matrix(pred_train_aa_ao_qda, train_response_aa_ao_qda))



confusion matrices for the LDA for aa and ao
[[439  56]
 [ 80 703]]
confusion matrices for the QDA for aa and ao
[[519   0]
 [  0 759]]
